export const CREATE_WIDGET = "CREATE_WIDGET";
export const FIND_ALL_WIDGETS = "FIND_ALL_WIDGETS";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const UPDATE_WIDGET = "UPDATE_WIDGET";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_SIZE = "UPDATE_SIZE";